# Generated by Django 3.0.5 on 2020-05-13 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birthDate',
            field=models.CharField(default='01/01/00', max_length=8, verbose_name='Date de naissance'),
        ),
    ]
