# Generated by Django 3.0.7 on 2020-07-20 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='secret_key',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name="Clé unique pour l'utilisateur"),
        ),
    ]
