# Generated by Django 3.0.7 on 2020-10-22 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_studentrequest_finalschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='followelement',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='followelement',
            name='coachBeenPaid',
            field=models.BooleanField(default=False),
        ),
    ]
