# Generated by Django 3.0.7 on 2020-07-30 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200720_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birthDate',
            field=models.CharField(default='01/01/00', max_length=10, verbose_name='Date de naissance'),
        ),
    ]
