# Generated by Django 3.0.7 on 2020-08-02 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200730_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=25, null=True, verbose_name='numéro de téléphone'),
        ),
    ]
