# Generated by Django 3.0.7 on 2020-11-01 16:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201022_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='followelement',
            name='endHour',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='followelement',
            name='startHour',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='followelement',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Date et heure du cours'),
        ),
    ]
