# Generated by Django 3.0.7 on 2020-08-05 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_transaction_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birthDate',
            field=models.CharField(default='01/01/00', max_length=25, verbose_name='Date de naissance'),
        ),
    ]
