# Generated by Django 3.0.7 on 2020-11-16 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_auto_20201113_2211"),
    ]

    operations = [
        migrations.AlterField(
            model_name="followelement",
            name="endHour",
            field=models.TimeField(default="12:00", verbose_name="Heure de fin"),
        ),
        migrations.AlterField(
            model_name="followelement",
            name="startHour",
            field=models.TimeField(default="10:00", verbose_name="Heure de début"),
        ),
    ]
