# Generated by Django 3.0.7 on 2020-11-16 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0007_auto_20201116_0956"),
    ]

    operations = [
        migrations.AlterField(
            model_name="followelement",
            name="coach",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coach_of",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
