# Generated by Django 3.0.7 on 2020-08-10 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200808_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachaccount',
            name='confirmedAccount',
            field=models.CharField(blank=True, default='a', max_length=1, verbose_name='Etat'),
        ),
        migrations.AlterField(
            model_name='coachaccount',
            name='nbStudents',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name="nombre d'étudiants du coach"),
        ),
    ]
