# Generated by Django 3.0.7 on 2020-08-11 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200810_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachaccount',
            name='confirmedAccount',
            field=models.CharField(blank=True, choices=[('a', '----'), ('b', 'Engagé'), ('c', 'Refusé')], default='a', max_length=1, verbose_name='Etat'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='school_level',
            field=models.CharField(blank=True, choices=[('a', 'Primaire'), ('b', '1ère humanité'), ('c', '2ème humanité'), ('d', '3ème humanité'), ('e', '4ème humanité'), ('f', '5ème humanité'), ('g', '6ème humanité'), ('h', 'Primaire'), ('i', 'Humanité'), ('j', 'Les deux'), ('k', 'autre')], max_length=1, null=True, verbose_name='Niveau scolaire'),
        ),
    ]
