# Generated by Django 3.0.7 on 2021-03-03 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20210207_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachrequestthrough',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.StudentRequest'),
        ),
        migrations.AlterField(
            model_name='studentrequest',
            name='coaches',
            field=models.ManyToManyField(blank=True, related_name='request_participated', through='users.CoachRequestThrough', to='users.CoachAccount'),
        ),
    ]
