# Generated by Django 3.0.7 on 2020-08-12 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20200811_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentaccount',
            name='resp_phone_number1',
            field=models.CharField(blank=True, default='', max_length=25, null=True, verbose_name="numéro de téléphone d'un responsable"),
        ),
        migrations.AddField(
            model_name='studentaccount',
            name='resp_phone_number2',
            field=models.CharField(blank=True, default='', max_length=25, null=True, verbose_name="numéro de téléphone d'un responsable"),
        ),
        migrations.AddField(
            model_name='studentaccount',
            name='resp_phone_number3',
            field=models.CharField(blank=True, default='', max_length=25, null=True, verbose_name="numéro de téléphone d'un responsable"),
        ),
    ]
