# Generated by Django 3.0.7 on 2020-08-12 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20200812_1021'),
        ('users', '0012_auto_20200812_1609'),
    ]

    operations = [
    ]
