# Generated by Django 3.0.7 on 2020-08-14 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0013_merge_20200812_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentaccount',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Coach', to=settings.AUTH_USER_MODEL),
        ),
    ]
