# Generated by Django 3.1.7 on 2021-07-27 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20210303_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Titre de la notification'),
        )
    ]
