# Generated by Django 3.1.7 on 2021-07-27 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20210727_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followelement',
            name='comments',
            field=models.TextField(default='Pas de commentaires', verbose_name='Matière(s) vue(s) au cours'),
        ),
    ]
