# Generated by Django 3.0.7 on 2020-08-28 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_remove_coachaccount_nbstudents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentrequest',
            name='choosenCoach',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.CoachAccount'),
        ),
        migrations.AlterField(
            model_name='studentrequest',
            name='coaches',
            field=models.ManyToManyField(related_name='request_participated', to='users.CoachAccount'),
        ),
    ]
