# Generated by Django 3.2.9 on 2022-02-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20210727_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentrequest',
            name='coaches',
            field=models.ManyToManyField(blank=True, related_name='request_participated', through='users.CoachRequestThrough', to='users.CoachAccount'),
        ),
    ]
