# Generated by Django 3.0.7 on 2020-08-28 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20200828_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentrequest',
            name='choosenCoach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.CoachAccount'),
        ),
    ]
