# Generated by Django 3.0.7 on 2020-08-28 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20200828_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentrequest',
            name='coaches',
            field=models.ManyToManyField(null=True, related_name='request_participated', to='users.CoachAccount'),
        ),
    ]
