# Generated by Django 3.0.7 on 2020-08-28 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20200828_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentaccount',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='users.CoachAccount'),
        ),
    ]
