version: '3.7'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile.prod
    command: gunicorn cad.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/static
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
    networks:
      - private
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
    networks:
      - private
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/static
    ports:
      - 1337:80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`newsite.cadcoursadomicile.com`)"
      - "traefik.http.routers.web.entrypoints=http"
      - "traefik.http.middlewares.web-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.web.middlewares=web-https-redirect"
      - "traefik.http.routers.web-secure.entrypoints=https"
      - "traefik.http.routers.web-secure.rule=Host(`newsite.cadcoursadomicile.com`)"
      - "traefik.http.routers.web-secure.tls=true"
      - "traefik.http.routers.web-secure.tls.certresolver=http"
      - "traefik.http.routers.web-secure.service=nginx-cad"
    depends_on:
      - web
    networks:
      - private
      - public

networks:
  private:
    driver: overlay
  public:
    external: true

volumes:
  postgres_data:
  static_volume:
