SECRET_KEY=***REMOVED***
DEBUG=0
SQL_ENGINE=django.db.backends.postgresql_psycopg2
SQL_DATABASE=***REMOVED***
SQL_USER=cad
SQL_PASSWORD=aa3fd666534bd13b1522c747959ddc27d987be02
SQL_HOST=***REMOVED***
SQL_PORT=5432
DJANGO_ALLOWED_HOSTS=cadcoursadomicile.com 127.0.0.1 [::1]

EMAIL_USE_TLS=true
EMAIL_HOST=smtp.gmail.com
EMAIL_PORT=***REMOVED***
EMAIL_HOST_USER=cadcoursadomicile@gmail.com
EMAIL_HOST_PASSWORD=azereza23.
