version: '3.7'

services:
  web:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    volumes:
      - static_volume:/srv/collected_static
    expose:
      - 8000
    env_file:
      - ./credentials/.env.dev
    depends_on:
      - db
    networks:
      - private
    restart: unless-stopped

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./credentials/.env.dev.db
    networks:
      - private
    restart: unless-stopped

  nginx:
    build: ../nginx
    volumes:
      - static_volume:/srv/collected_static
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.entrypoints=http"
      - "traefik.http.routers.web.rule=Host(`dev.cadcours.com`)"
      - "traefik.http.middlewares.web-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.web.middlewares=web-https-redirect"
      - "traefik.http.routers.web-secure.entrypoints=https"
      - "traefik.http.routers.web-secure.rule=Host(`dev.cadcours.com`)"
      - "traefik.http.routers.web-secure.tls=true"
      - "traefik.http.routers.web-secure.tls.certresolver=http"
      - "traefik.http.routers.web-secure.service=nginx-cad-dev@docker"
      - "traefik.docker.network=traefik-proxy"
    depends_on:
      - web
    networks:
      - private
      - public
      - traefik-proxy
    restart: unless-stopped

networks:
  private:
    driver: overlay
  public:
    external: true
  traefik-proxy:
    external: true

volumes:
  postgres_data:
  static_volume:
