# Generated by Django 3.0.7 on 2020-08-14 14:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('default', '0003_message_seen'),
    ]

    operations = [
        migrations.CreateModel(
            name='mailingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Utilisateurs intéréssés')),
            ],
        ),
    ]
