# Generated by Django 3.1.7 on 2021-07-27 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0007_auto_20200912_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='role',
            field=models.CharField(choices=[('a', "verification de l'adresse mail (coach et élèvre)"), ('b', 'mail de bienvenue (élève)'), ('c', 'proposition desinscription (élève)'), ('d', 'solde dangereux (élève)'), ('e', 'proposition de mission (coach)'), ('f', 'attribution de mission (coach)'), ('g', 'mission attribuée à un autre coach (coach)'), ('h', 'Template non automatique'), ('i', 'Message envoyé'), ('j', 'Votre planning de cours (élève)')], max_length=1, verbose_name='Role du mail'),
        ),
    ]
