name: Deploy 

on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ls -a via ssh
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd /home/ubuntu/docker/apps/CAD
            ./build_prod.sh
          host: ${{ secrets.HOST }}
          user: root
          key: ${{ secrets.PRIVATE_KEY}}
