name: Build 

on:
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: upgrading pip & Installing pip packages
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: flake8
      run: sudo apt install flake8 -y && flake8 --ignore=E501,F401 .

    - name: executing tests
      run: python3 manage.py test
