name: Build 

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: upgrading pip & Installing pip packages
      run: |
        pip3 install --upgrade pip
        pip3 install -r requirements.txt

    - name: flake8
      run: flake8 --ignore=E501,F401 .

    - name: executing tests
      run: |
        mkdir logs && touch logs/cad.log
        python3 manage.py test
